app:
    cors:
        allowed-origins: ${ORIGIN}

jwt:
  secret: ${JWTKEY}
  expiration: ${EXPIRE}

python:
  url: ${PYTHON_URL}

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${PROFILE}
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/pdv?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: ${DDL}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          '[provider_disables_autocommit]': true
        '[format_sql]': true
    database: mysql

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: ${SWAGGER_DOC}
    api-docs:
      enabled: ${SWAGGER_DOC}